<?php
@header('Content-Type: text/html; charset=tis-620');


?>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=tis-620" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<?php
//$showslip = '255703';
$showslip = Show_Slip(date('d-m-Y'));

$strSQL = "SELECT 
					LT.LOANTYPE_DESC AS LOANTYPE_DESC,
					LNM.LOANCONTRACT_NO AS LOANCONTRACT_NO,
					LNM.LOANAPPROVE_AMT AS LOANAPPROVE_AMT,
					convert(varchar,DAY(LNM.STARTCONT_DATE)) + '/' +
				    convert(varchar,month(LNM.STARTCONT_DATE)) + '/' +
					SUBSTRING(convert(varchar,year(LNM.STARTCONT_DATE)+ 543),3,2) AS STARTCONT_DATE,
					LNM.PERIOD_PAYAMT AS PERIOD_PAYAMT,
					(SELECT SUM(PRINCIPAL_PAYMENT) FROM KPTEMPRECEIVEDET WHERE LOANCONTRACT_NO=LNM.LOANCONTRACT_NO AND RECV_PERIOD='$showslip') AS PRINCIPAL_PAYMENT, 
					(SELECT SUM(INTEREST_PAYMENT) FROM KPTEMPRECEIVEDET WHERE LOANCONTRACT_NO=LNM.LOANCONTRACT_NO AND RECV_PERIOD='$showslip') AS INTEREST_PAYMENT,
					((SELECT SUM(PRINCIPAL_PAYMENT) FROM KPTEMPRECEIVEDET WHERE LOANCONTRACT_NO=LNM.LOANCONTRACT_NO AND RECV_PERIOD='$showslip')+
					(SELECT SUM(INTEREST_PAYMENT) FROM KPTEMPRECEIVEDET WHERE LOANCONTRACT_NO=LNM.LOANCONTRACT_NO AND RECV_PERIOD='$showslip')) AS TOTALPAY,
					LNM.PRINCIPAL_BALANCE AS PRINCIPAL_BALANCE,
					(((LNM.LOANAPPROVE_AMT-LNM.PRINCIPAL_BALANCE)*100)/LNM.LOANAPPROVE_AMT) AS PAY_PERSENT
				FROM 
					LNCONTMASTER LNM , LNLOANTYPE LT
				WHERE 
					LNM.LOANTYPE_CODE = LT.LOANTYPE_CODE 
					AND LNM.MEMBER_NO = '$member_no'
					AND LT.LOANGROUP_CODE = '$loan_code'
					AND LNM.CONTRACT_STATUS = '1'
					AND LNM.STARTCONT_DATE IS NOT NULL " ;

		
		$resultData = sqlsrv_query($objConnect,$strSQL); 

?>